### ISSUE TITLE
Change how the Daily and Weekly forms are in current design.

### ISSUE THREAD

**Issue by Pawel062** [CIMDBORG/CIMMigrationProject#12] opened 2020-01-21 19:46 UTC
2 propositions:

- 3 separate forms

- 1 form with tabs (similar in design to github) or radial buttons to choose between Weekday Daily, Saturday Daily, and Saturday Weekly scenarios. Please note: I checked the current database and all 3 types have 4 tracking numbers and the only variations are if there is a Saturday verification button AND what the bottom shows in terms of notes/comments. We can have the code hide and show those items depending on which of the 3 options are chosen.

**Comment by qdd8jtl** [comment] 2020-01-21 20:52
There definitely needs to be 3 separate forms, but the design should remain the same across all 3.  The notes should be visible on both Daily and Saturday Daily forms since these are ultimately the same scenarios verified throughout the week.

For Saturday Daily and Saturday Weekly forms, these should only be visible to Supervisors and above.

**Comment by Pawel062** [comment] 2020-01-21 21:28
My idea for 1 form is more of a background template than anything. It will pull up 3 "seperate" forms but behind the scenes it will use 1 template for it as you mentioned. The 1 template makes it easier for problem solving while still separating the pages. It might be better if I explain it in person or debunk my idea if it wont work.

**Comment by milleniumchilld** [comment] 2020-01-22 13:06
Morning everyone,

I was out of office yesterday so I did not get a chance to respond. I would like for us to discuss the changes in this week meeting if that is ok. So I can have a general idea of what is expected.

**Comment by qdd8jtl** [comment] 2020-01-22 13:11
Agreed!  If we are changing the design of the form and moving away from what Sophia originally mocked up, we need new mock ups.  Also, isn't Issue #13 a duplicate of this?

**Comment by Pawel062** [comment] 2020-01-22 13:19
this one I created for us to discuss how to change the 2 forms we have now into 1 or 3 and then #13 was created separately to brainstorm how to fill the dead space we have in the current design. I thought it is better to separate it so it is easier to keep up with which part of the topic we are discussing. We can definitely discuss this at our meeting Friday but I wanted to get some ideas out there before the meeting.

**Comment by Pawel062** [comment] 2020-01-22 14:02
After discussing this with Jan-Marie, we will move forward with 1 form and tabs to switch between the 3 variations. We can move to the design then. 

Sophia can you take the current form and mockup a evolution of it: 
--Jan-Marie suggested keeping the bold items still at the top (title, source, country, assigned to, alt auditor, description, and id) but add 3 tabs above it similar to how gethub has it. 
--These tabs should be named daily, saturday daily, and saturday weekly to keep naming convention in line with BIG. 
--Then move the 4 tracking numbers to the left and list them 1 after the other with a line to divide the incented / non-incented. 
--The results and defect will then be moved over to the right and should be on the same "line" as tracking # 1 while the notes below it with a big text entry box.

**Comment by Pawel062** [comment] 2020-01-22 16:10
That is perfect!

**Comment by qdd8jtl** [comment] 2020-01-22 18:11
I like it!  Nice job.

**Closed** 2020-01-24 19:21 UTC
Labels: Design
