### ISSUE TITLE
Weekly Review With Applications Item Browsing

### ISSUE THREAD

**Issue by carrubba24** [CIMDBORG/CIMMigrationProject#46] opened 2020-02-13 13:42 UTC
When clicking previous/next item arrows in the weekly review screen , some cells pull data for next item, but most cells seem 'stuck' on the first item when the screen was launched. May have something to do 'Update Successful' message that populates when clicking the arrows.

**Comment by carrubba24** [comment] 2020-02-13 13:47
Looks like it is definitely related to the 'Update Successful' message, because all of my items now have the same title. 
![image](https://user-images.githubusercontent.com/59064371/74441096-3bb65c80-4e3d-11ea-85ad-e1c877194c27.png) <br/>
Please use caution, I advise staying away from the 'Weekly Review with Applications' screen until this is resolved.

**Comment by mortii09** [comment] 2020-02-13 14:00
i like to add i am finally getting updates via email!

**Comment by mortii09** [comment] 2020-02-13 14:03
dom, wait this has completely updated your data for real!? @brcox90 @qdd8jtl @mikey2695

**Comment by carrubba24** [comment] 2020-02-13 14:07
Unfortunately yes, but luckily I save a report of open items week to week so I have a backup.

**Comment by mikey2695** [comment] 2020-02-13 14:07
Can confirm. Code red. No one touch weekly review w/apps. On it.

**Comment by mortii09** [comment] 2020-02-13 14:10
let me know if you need my eyeballs, and i can give backup...

**Comment by brcox90** [comment] 2020-02-13 14:14
I fixed it. This was actually happening with the back button. Something that needed to be commented out wasn't (**COMPLETELY ON ME**). We should probably be pushing this update ASAP. 

@NickD0w @mikey2695 @qdd8jtl

**Comment by qdd8jtl** [comment] 2020-02-13 14:19
As long as we are sure the issue is completely fixed, please get the update out sooner than later.  We might want to send an email to the team just to let them know, too.  Thanks for addressing this so quickly with all the crazy going on with the migration.

**Comment by NickD0w** [comment] 2020-02-13 14:20
Agreed this needs to go in... @mikey2695 @mortii09  can you verify the fix?

**Comment by mortii09** [comment] 2020-02-13 14:31
@NickD0w @qdd8jtl yes i will test this, and agree this will need to be confirmed 100 percent before posting.. i will need to see this step by step to confirm and why the error occured. 

I have a feeling we maybe in a disconnect about how github is supposed to be utilized i will call

**Comment by brcox90** [comment] 2020-02-13 16:16
Updated and fix has been pushed

**Closed by brcox90** 2020-02-13 16:16 UTC
Labels: Billing, Defect, bug
